-- MySQL Script generated by MySQL Workbench
-- Sun Jul 24 19:47:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mySqlDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mySqlDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mySqlDB` DEFAULT CHARACTER SET utf8 ;
USE `mySqlDB` ;

-- -----------------------------------------------------
-- Table `mySqlDB`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mySqlDB`.`product_categories` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mySqlDB`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mySqlDB`.`images` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `image_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mySqlDB`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mySqlDB`.`categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id_category`),
  CONSTRAINT `categories`
    FOREIGN KEY (`id_category`)
    REFERENCES `mySqlDB`.`product_categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mySqlDB`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mySqlDB`.`image` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image_path` VARCHAR(45) NOT NULL,
  `alt` VARCHAR(45) NULL,
  PRIMARY KEY (`image_id`),
  CONSTRAINT `image`
    FOREIGN KEY (`image_id`)
    REFERENCES `mySqlDB`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mySqlDB`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mySqlDB`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `price` DECIMAL(8) NOT NULL,
  `category_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  `price_with_promoCode` DECIMAL NOT NULL,
  `price_with_discount` DECIMAL NOT NULL,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `product_cat_idx` (`category_id` ASC) VISIBLE,
  INDEX `image_idx` (`image_id` ASC) VISIBLE,
  CONSTRAINT `product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mySqlDB`.`product_categories` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `images`
    FOREIGN KEY (`product_id`)
    REFERENCES `mySqlDB`.`images` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_cat`
    FOREIGN KEY (`category_id`)
    REFERENCES `mySqlDB`.`categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `image`
    FOREIGN KEY (`image_id`)
    REFERENCES `mySqlDB`.`image` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mySqlDB` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `mySqlDB`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
